'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type FeedlogButtonCustomEvent } from "@feedlog-toolkit/webcomponents";
import { FeedlogBadge as FeedlogBadgeElement, defineCustomElement as defineFeedlogBadge } from "@feedlog-toolkit/webcomponents/dist/components/feedlog-badge.js";
import { FeedlogButton as FeedlogButtonElement, defineCustomElement as defineFeedlogButton } from "@feedlog-toolkit/webcomponents/dist/components/feedlog-button.js";
import { FeedlogCard as FeedlogCardElement, defineCustomElement as defineFeedlogCard } from "@feedlog-toolkit/webcomponents/dist/components/feedlog-card.js";
import { FeedlogGithubIssuesClient as FeedlogGithubIssuesClientElement, defineCustomElement as defineFeedlogGithubIssuesClient } from "@feedlog-toolkit/webcomponents/dist/components/feedlog-github-issues-client.js";
import { FeedlogGithubIssues as FeedlogGithubIssuesElement, defineCustomElement as defineFeedlogGithubIssues } from "@feedlog-toolkit/webcomponents/dist/components/feedlog-github-issues.js";
import { FeedlogIssuesList as FeedlogIssuesListElement, defineCustomElement as defineFeedlogIssuesList } from "@feedlog-toolkit/webcomponents/dist/components/feedlog-issues-list.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type FeedlogBadgeEvents = NonNullable<unknown>;

export const FeedlogBadge: StencilReactComponent<FeedlogBadgeElement, FeedlogBadgeEvents> = /*@__PURE__*/ createComponent<FeedlogBadgeElement, FeedlogBadgeEvents>({
    tagName: 'feedlog-badge',
    elementClass: FeedlogBadgeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as FeedlogBadgeEvents,
    defineCustomElement: defineFeedlogBadge
});

type FeedlogButtonEvents = { onFeedlogClick: EventName<FeedlogButtonCustomEvent<MouseEvent>> };

export const FeedlogButton: StencilReactComponent<FeedlogButtonElement, FeedlogButtonEvents> = /*@__PURE__*/ createComponent<FeedlogButtonElement, FeedlogButtonEvents>({
    tagName: 'feedlog-button',
    elementClass: FeedlogButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onFeedlogClick: 'feedlogClick' } as FeedlogButtonEvents,
    defineCustomElement: defineFeedlogButton
});

type FeedlogCardEvents = NonNullable<unknown>;

export const FeedlogCard: StencilReactComponent<FeedlogCardElement, FeedlogCardEvents> = /*@__PURE__*/ createComponent<FeedlogCardElement, FeedlogCardEvents>({
    tagName: 'feedlog-card',
    elementClass: FeedlogCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as FeedlogCardEvents,
    defineCustomElement: defineFeedlogCard
});

type FeedlogGithubIssuesEvents = {
    onFeedlogUpvote: EventName<CustomEvent<{
        issueId: string;
        currentUpvoted: boolean;
        currentCount: number;
    }>>,
    onFeedlogThemeChange: EventName<CustomEvent<'light' | 'dark'>>,
    onFeedlogLoadMore: EventName<CustomEvent<void>>
};

export const FeedlogGithubIssues: StencilReactComponent<FeedlogGithubIssuesElement, FeedlogGithubIssuesEvents> = /*@__PURE__*/ createComponent<FeedlogGithubIssuesElement, FeedlogGithubIssuesEvents>({
    tagName: 'feedlog-github-issues',
    elementClass: FeedlogGithubIssuesElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onFeedlogUpvote: 'feedlogUpvote',
        onFeedlogThemeChange: 'feedlogThemeChange',
        onFeedlogLoadMore: 'feedlogLoadMore'
    } as FeedlogGithubIssuesEvents,
    defineCustomElement: defineFeedlogGithubIssues
});

type FeedlogGithubIssuesClientEvents = {
    onFeedlogUpvote: EventName<CustomEvent<{ issueId: string; upvoted: boolean; upvoteCount: number }>>,
    onFeedlogThemeChange: EventName<CustomEvent<'light' | 'dark'>>,
    onFeedlogError: EventName<CustomEvent<{ error: string; code?: number }>>
};

export const FeedlogGithubIssuesClient: StencilReactComponent<FeedlogGithubIssuesClientElement, FeedlogGithubIssuesClientEvents> = /*@__PURE__*/ createComponent<FeedlogGithubIssuesClientElement, FeedlogGithubIssuesClientEvents>({
    tagName: 'feedlog-github-issues-client',
    elementClass: FeedlogGithubIssuesClientElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onFeedlogUpvote: 'feedlogUpvote',
        onFeedlogThemeChange: 'feedlogThemeChange',
        onFeedlogError: 'feedlogError'
    } as FeedlogGithubIssuesClientEvents,
    defineCustomElement: defineFeedlogGithubIssuesClient
});

type FeedlogIssuesListEvents = {
    onFeedlogUpvote: EventName<CustomEvent<{
        issueId: string;
        currentUpvoted: boolean;
        currentCount: number;
    }>>
};

export const FeedlogIssuesList: StencilReactComponent<FeedlogIssuesListElement, FeedlogIssuesListEvents> = /*@__PURE__*/ createComponent<FeedlogIssuesListElement, FeedlogIssuesListEvents>({
    tagName: 'feedlog-issues-list',
    elementClass: FeedlogIssuesListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onFeedlogUpvote: 'feedlogUpvote' } as FeedlogIssuesListEvents,
    defineCustomElement: defineFeedlogIssuesList
});
