/**
 * React bindings for Feedlog Toolkit Web Components
 *
 * This package provides React components that wrap the Stencil web components.
 * Components are auto-generated from the Stencil build process.
 */

// Re-export all React components generated by Stencil
export * from './components/stencil-generated';

// Define custom elements (required for web components to work)
import { defineCustomElements } from '@feedlog-toolkit/webcomponents/loader';

// Auto-define custom elements when this module is imported
if (typeof window !== 'undefined') {
  defineCustomElements();
}
