/**
 * Vue bindings for Feedlog Toolkit Web Components
 * 
 * This package provides Vue components that wrap the Stencil web components.
 * Components are auto-generated from the Stencil build process.
 */

// Re-export all Vue components generated by Stencil
export * from './components';

// Define custom elements (required for web components to work)
import { defineCustomElements } from '@feedlog-toolkit/webcomponents/loader';

// Auto-define custom elements when this module is imported
if (typeof window !== 'undefined') {
  defineCustomElements();
}

// Vue plugin installation function
import type { App } from 'vue';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function install(_app: App): void {
  // Custom elements are automatically registered via defineCustomElements
  // Additional Vue-specific setup can be added here if needed
}

