/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { FeedlogIssue as FeedlogIssueType, GetIssueUrlFn, SortBy } from '@feedlog-ai/core';
export { FeedlogIssue as FeedlogIssueType, GetIssueUrlFn, SortBy } from '@feedlog-ai/core';
export namespace Components {
  /**
   * Feedlog Badge Component
   * A label component with variant support for different styles.
   */
  interface FeedlogBadge {
    /**
     * Badge variant style
     * @default 'default'
     */
    variant: 'default' | 'destructive' | 'enhancement' | 'secondary';
  }
  /**
   * Feedlog Button Component
   * A button component with variant and size support.
   */
  interface FeedlogButton {
    /**
     * Disabled state
     * @default false
     */
    disabled: boolean;
    /**
     * Button size
     * @default 'default'
     */
    size: 'default' | 'sm' | 'lg';
    /**
     * Button type
     * @default 'button'
     */
    type: 'button' | 'submit' | 'reset';
    /**
     * Button variant style
     * @default 'default'
     */
    variant: 'default' | 'outline' | 'ghost' | 'destructive';
  }
  /**
   * Feedlog Card Component
   * A reusable card container component with header and content areas.
   */
  interface FeedlogCard {}
  /**
   * Feedlog Issue Component
   * A component for displaying a single GitHub issue.
   */
  interface FeedlogIssue {
    /**
     * The issue to display
     */
    issue: FeedlogIssueType;
    /**
     * Optional URL for the GitHub issue. When provided along with githubIssueLink, shows a "View on GitHub" button. Required because owner is no longer in the API response.
     */
    issueUrl?: string | null;
    /**
     * Theme variant: 'light' or 'dark'
     * @default 'light'
     */
    theme: 'light' | 'dark';
  }
  /**
   * Feedlog Issues Component
   * Component for displaying issues with support for bugs and enhancements.
   * Includes full list rendering, loading/error states, and pagination support.
   */
  interface FeedlogIssues {
    /**
     * Empty state message. Defaults to "Check back later for new updates.".
     */
    emptyStateMessage?: string;
    /**
     * Empty state title. Defaults to "No updates yet".
     */
    emptyStateTitle?: string;
    /**
     * Error message - shows error state when set
     * @default null
     */
    error: string | null;
    /**
     * Optional callback to resolve issue URL when githubIssueLink is not available. Required because repository.owner was removed from the API for privacy.
     */
    getIssueUrl?: GetIssueUrlFn;
    /**
     * Whether there are more issues to load
     * @default false
     */
    hasMore: boolean;
    /**
     * Custom heading for the issues section
     */
    heading?: string;
    /**
     * Whether more issues are currently loading
     * @default false
     */
    isLoadingMore: boolean;
    /**
     * Array of issues to display
     * @default []
     */
    issues: FeedlogIssueType[];
    /**
     * Page size for issues list pagination. When set, enables pagination when issues exceed this limit.
     */
    limit?: number;
    /**
     * Loading state - shows loading indicator when true
     * @default false
     */
    loading: boolean;
    /**
     * Maximum width of the container
     * @default '42rem'
     */
    maxWidth: string;
    /**
     * Custom subtitle for the issues section
     */
    subtitle?: string;
    /**
     * Theme variant: 'light' or 'dark'
     * @default 'light'
     */
    theme: 'light' | 'dark';
  }
  /**
   * Feedlog Issues Client Component
   * A component for displaying issues fetched using the Feedlog SDK.
   * This component uses the SDK internally to fetch data and delegates to feedlog-issues for rendering.
   */
  interface FeedlogIssuesClient {
    /**
     * API key for Feedlog authentication (required) The API key determines which repositories' issues are fetched
     */
    apiKey: string;
    /**
     * Empty state message (e.g. "Check back later for new updates.")
     */
    emptyStateMessage?: string;
    /**
     * Empty state title (e.g. "No updates yet")
     */
    emptyStateTitle?: string;
    /**
     * Custom API endpoint
     */
    endpoint?: string;
    /**
     * Optional callback to resolve issue URL when githubIssueLink is not available. Required because repository.owner was removed from the API for privacy.
     */
    getIssueUrl?: GetIssueUrlFn;
    /**
     * Custom heading for the issues section
     */
    heading?: string;
    /**
     * Maximum number of issues to fetch (1-100, default 10)
     */
    limit?: number;
    /**
     * Maximum width of the container
     * @default '42rem'
     */
    maxWidth: string;
    /**
     * Sort issues by field: 'createdAt' or 'updatedAt'
     */
    sortBy?: SortBy;
    /**
     * Custom subtitle for the issues section
     */
    subtitle?: string;
    /**
     * Theme variant: 'light' or 'dark'
     * @default 'light'
     */
    theme: 'light' | 'dark';
    /**
     * Filter issues by type: 'bug' or 'enhancement'
     */
    type?: 'bug' | 'enhancement';
  }
  /**
   * Feedlog Issues List Component
   * A component for displaying a list of GitHub issues with support for bugs and enhancements.
   */
  interface FeedlogIssuesList {
    /**
     * Empty state message. When provided with emptyStateTitle, shows a richer empty state with illustration.
     */
    emptyStateMessage?: string;
    /**
     * Empty state title. When provided with emptyStateMessage, shows a richer empty state with illustration.
     */
    emptyStateTitle?: string;
    /**
     * Optional callback to resolve GitHub issue URL when githubIssueLink is not available.
     */
    getIssueUrl?: GetIssueUrlFn;
    /**
     * Array of issues to display
     * @default []
     */
    issues: FeedlogIssueType[];
    /**
     * Page size (items per page). When set, enables pagination when issues exceed this limit.
     */
    limit?: number;
    /**
     * Theme variant: 'light' or 'dark'
     * @default 'light'
     */
    theme: 'light' | 'dark';
  }
}
export interface FeedlogButtonCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLFeedlogButtonElement;
}
export interface FeedlogIssueCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLFeedlogIssueElement;
}
export interface FeedlogIssuesCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLFeedlogIssuesElement;
}
export interface FeedlogIssuesClientCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLFeedlogIssuesClientElement;
}
export interface FeedlogIssuesListCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLFeedlogIssuesListElement;
}
declare global {
  /**
   * Feedlog Badge Component
   * A label component with variant support for different styles.
   */
  interface HTMLFeedlogBadgeElement extends Components.FeedlogBadge, HTMLStencilElement {}
  var HTMLFeedlogBadgeElement: {
    prototype: HTMLFeedlogBadgeElement;
    new (): HTMLFeedlogBadgeElement;
  };
  interface HTMLFeedlogButtonElementEventMap {
    feedlogClick: MouseEvent;
  }
  /**
   * Feedlog Button Component
   * A button component with variant and size support.
   */
  interface HTMLFeedlogButtonElement extends Components.FeedlogButton, HTMLStencilElement {
    addEventListener<K extends keyof HTMLFeedlogButtonElementEventMap>(
      type: K,
      listener: (
        this: HTMLFeedlogButtonElement,
        ev: FeedlogButtonCustomEvent<HTMLFeedlogButtonElementEventMap[K]>
      ) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLFeedlogButtonElementEventMap>(
      type: K,
      listener: (
        this: HTMLFeedlogButtonElement,
        ev: FeedlogButtonCustomEvent<HTMLFeedlogButtonElementEventMap[K]>
      ) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLFeedlogButtonElement: {
    prototype: HTMLFeedlogButtonElement;
    new (): HTMLFeedlogButtonElement;
  };
  /**
   * Feedlog Card Component
   * A reusable card container component with header and content areas.
   */
  interface HTMLFeedlogCardElement extends Components.FeedlogCard, HTMLStencilElement {}
  var HTMLFeedlogCardElement: {
    prototype: HTMLFeedlogCardElement;
    new (): HTMLFeedlogCardElement;
  };
  interface HTMLFeedlogIssueElementEventMap {
    feedlogUpvote: {
      issueId: string;
      currentUpvoted: boolean;
      currentCount: number;
    };
  }
  /**
   * Feedlog Issue Component
   * A component for displaying a single GitHub issue.
   */
  interface HTMLFeedlogIssueElement extends Components.FeedlogIssue, HTMLStencilElement {
    addEventListener<K extends keyof HTMLFeedlogIssueElementEventMap>(
      type: K,
      listener: (
        this: HTMLFeedlogIssueElement,
        ev: FeedlogIssueCustomEvent<HTMLFeedlogIssueElementEventMap[K]>
      ) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLFeedlogIssueElementEventMap>(
      type: K,
      listener: (
        this: HTMLFeedlogIssueElement,
        ev: FeedlogIssueCustomEvent<HTMLFeedlogIssueElementEventMap[K]>
      ) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLFeedlogIssueElement: {
    prototype: HTMLFeedlogIssueElement;
    new (): HTMLFeedlogIssueElement;
  };
  interface HTMLFeedlogIssuesElementEventMap {
    feedlogUpvote: {
      issueId: string;
      currentUpvoted: boolean;
      currentCount: number;
    };
    feedlogLoadMore: void;
  }
  /**
   * Feedlog Issues Component
   * Component for displaying issues with support for bugs and enhancements.
   * Includes full list rendering, loading/error states, and pagination support.
   */
  interface HTMLFeedlogIssuesElement extends Components.FeedlogIssues, HTMLStencilElement {
    addEventListener<K extends keyof HTMLFeedlogIssuesElementEventMap>(
      type: K,
      listener: (
        this: HTMLFeedlogIssuesElement,
        ev: FeedlogIssuesCustomEvent<HTMLFeedlogIssuesElementEventMap[K]>
      ) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLFeedlogIssuesElementEventMap>(
      type: K,
      listener: (
        this: HTMLFeedlogIssuesElement,
        ev: FeedlogIssuesCustomEvent<HTMLFeedlogIssuesElementEventMap[K]>
      ) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLFeedlogIssuesElement: {
    prototype: HTMLFeedlogIssuesElement;
    new (): HTMLFeedlogIssuesElement;
  };
  interface HTMLFeedlogIssuesClientElementEventMap {
    feedlogUpvote: { issueId: string; upvoted: boolean; upvoteCount: number };
    feedlogError: { error: string; code?: number };
  }
  /**
   * Feedlog Issues Client Component
   * A component for displaying issues fetched using the Feedlog SDK.
   * This component uses the SDK internally to fetch data and delegates to feedlog-issues for rendering.
   */
  interface HTMLFeedlogIssuesClientElement
    extends Components.FeedlogIssuesClient, HTMLStencilElement {
    addEventListener<K extends keyof HTMLFeedlogIssuesClientElementEventMap>(
      type: K,
      listener: (
        this: HTMLFeedlogIssuesClientElement,
        ev: FeedlogIssuesClientCustomEvent<HTMLFeedlogIssuesClientElementEventMap[K]>
      ) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLFeedlogIssuesClientElementEventMap>(
      type: K,
      listener: (
        this: HTMLFeedlogIssuesClientElement,
        ev: FeedlogIssuesClientCustomEvent<HTMLFeedlogIssuesClientElementEventMap[K]>
      ) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLFeedlogIssuesClientElement: {
    prototype: HTMLFeedlogIssuesClientElement;
    new (): HTMLFeedlogIssuesClientElement;
  };
  interface HTMLFeedlogIssuesListElementEventMap {
    feedlogUpvote: {
      issueId: string;
      currentUpvoted: boolean;
      currentCount: number;
    };
  }
  /**
   * Feedlog Issues List Component
   * A component for displaying a list of GitHub issues with support for bugs and enhancements.
   */
  interface HTMLFeedlogIssuesListElement extends Components.FeedlogIssuesList, HTMLStencilElement {
    addEventListener<K extends keyof HTMLFeedlogIssuesListElementEventMap>(
      type: K,
      listener: (
        this: HTMLFeedlogIssuesListElement,
        ev: FeedlogIssuesListCustomEvent<HTMLFeedlogIssuesListElementEventMap[K]>
      ) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLFeedlogIssuesListElementEventMap>(
      type: K,
      listener: (
        this: HTMLFeedlogIssuesListElement,
        ev: FeedlogIssuesListCustomEvent<HTMLFeedlogIssuesListElementEventMap[K]>
      ) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLFeedlogIssuesListElement: {
    prototype: HTMLFeedlogIssuesListElement;
    new (): HTMLFeedlogIssuesListElement;
  };
  interface HTMLElementTagNameMap {
    'feedlog-badge': HTMLFeedlogBadgeElement;
    'feedlog-button': HTMLFeedlogButtonElement;
    'feedlog-card': HTMLFeedlogCardElement;
    'feedlog-issue': HTMLFeedlogIssueElement;
    'feedlog-issues': HTMLFeedlogIssuesElement;
    'feedlog-issues-client': HTMLFeedlogIssuesClientElement;
    'feedlog-issues-list': HTMLFeedlogIssuesListElement;
  }
}
declare namespace LocalJSX {
  /**
   * Feedlog Badge Component
   * A label component with variant support for different styles.
   */
  interface FeedlogBadge {
    /**
     * Badge variant style
     * @default 'default'
     */
    variant?: 'default' | 'destructive' | 'enhancement' | 'secondary';
  }
  /**
   * Feedlog Button Component
   * A button component with variant and size support.
   */
  interface FeedlogButton {
    /**
     * Disabled state
     * @default false
     */
    disabled?: boolean;
    /**
     * Event emitted when button is clicked
     */
    onFeedlogClick?: (event: FeedlogButtonCustomEvent<MouseEvent>) => void;
    /**
     * Button size
     * @default 'default'
     */
    size?: 'default' | 'sm' | 'lg';
    /**
     * Button type
     * @default 'button'
     */
    type?: 'button' | 'submit' | 'reset';
    /**
     * Button variant style
     * @default 'default'
     */
    variant?: 'default' | 'outline' | 'ghost' | 'destructive';
  }
  /**
   * Feedlog Card Component
   * A reusable card container component with header and content areas.
   */
  interface FeedlogCard {}
  /**
   * Feedlog Issue Component
   * A component for displaying a single GitHub issue.
   */
  interface FeedlogIssue {
    /**
     * The issue to display
     */
    issue: FeedlogIssueType;
    /**
     * Optional URL for the GitHub issue. When provided along with githubIssueLink, shows a "View on GitHub" button. Required because owner is no longer in the API response.
     */
    issueUrl?: string | null;
    /**
     * Event emitted when the issue is upvoted
     */
    onFeedlogUpvote?: (
      event: FeedlogIssueCustomEvent<{
        issueId: string;
        currentUpvoted: boolean;
        currentCount: number;
      }>
    ) => void;
    /**
     * Theme variant: 'light' or 'dark'
     * @default 'light'
     */
    theme?: 'light' | 'dark';
  }
  /**
   * Feedlog Issues Component
   * Component for displaying issues with support for bugs and enhancements.
   * Includes full list rendering, loading/error states, and pagination support.
   */
  interface FeedlogIssues {
    /**
     * Empty state message. Defaults to "Check back later for new updates.".
     */
    emptyStateMessage?: string;
    /**
     * Empty state title. Defaults to "No updates yet".
     */
    emptyStateTitle?: string;
    /**
     * Error message - shows error state when set
     * @default null
     */
    error?: string | null;
    /**
     * Optional callback to resolve issue URL when githubIssueLink is not available. Required because repository.owner was removed from the API for privacy.
     */
    getIssueUrl?: GetIssueUrlFn;
    /**
     * Whether there are more issues to load
     * @default false
     */
    hasMore?: boolean;
    /**
     * Custom heading for the issues section
     */
    heading?: string;
    /**
     * Whether more issues are currently loading
     * @default false
     */
    isLoadingMore?: boolean;
    /**
     * Array of issues to display
     * @default []
     */
    issues?: FeedlogIssueType[];
    /**
     * Page size for issues list pagination. When set, enables pagination when issues exceed this limit.
     */
    limit?: number;
    /**
     * Loading state - shows loading indicator when true
     * @default false
     */
    loading?: boolean;
    /**
     * Maximum width of the container
     * @default '42rem'
     */
    maxWidth?: string;
    /**
     * Event emitted to load more issues
     */
    onFeedlogLoadMore?: (event: FeedlogIssuesCustomEvent<void>) => void;
    /**
     * Event emitted when an issue is upvoted
     */
    onFeedlogUpvote?: (
      event: FeedlogIssuesCustomEvent<{
        issueId: string;
        currentUpvoted: boolean;
        currentCount: number;
      }>
    ) => void;
    /**
     * Custom subtitle for the issues section
     */
    subtitle?: string;
    /**
     * Theme variant: 'light' or 'dark'
     * @default 'light'
     */
    theme?: 'light' | 'dark';
  }
  /**
   * Feedlog Issues Client Component
   * A component for displaying issues fetched using the Feedlog SDK.
   * This component uses the SDK internally to fetch data and delegates to feedlog-issues for rendering.
   */
  interface FeedlogIssuesClient {
    /**
     * API key for Feedlog authentication (required) The API key determines which repositories' issues are fetched
     */
    apiKey: string;
    /**
     * Empty state message (e.g. "Check back later for new updates.")
     */
    emptyStateMessage?: string;
    /**
     * Empty state title (e.g. "No updates yet")
     */
    emptyStateTitle?: string;
    /**
     * Custom API endpoint
     */
    endpoint?: string;
    /**
     * Optional callback to resolve issue URL when githubIssueLink is not available. Required because repository.owner was removed from the API for privacy.
     */
    getIssueUrl?: GetIssueUrlFn;
    /**
     * Custom heading for the issues section
     */
    heading?: string;
    /**
     * Maximum number of issues to fetch (1-100, default 10)
     */
    limit?: number;
    /**
     * Maximum width of the container
     * @default '42rem'
     */
    maxWidth?: string;
    /**
     * Event emitted on error
     */
    onFeedlogError?: (
      event: FeedlogIssuesClientCustomEvent<{ error: string; code?: number }>
    ) => void;
    /**
     * Event emitted when an issue is upvoted
     */
    onFeedlogUpvote?: (
      event: FeedlogIssuesClientCustomEvent<{
        issueId: string;
        upvoted: boolean;
        upvoteCount: number;
      }>
    ) => void;
    /**
     * Sort issues by field: 'createdAt' or 'updatedAt'
     */
    sortBy?: SortBy;
    /**
     * Custom subtitle for the issues section
     */
    subtitle?: string;
    /**
     * Theme variant: 'light' or 'dark'
     * @default 'light'
     */
    theme?: 'light' | 'dark';
    /**
     * Filter issues by type: 'bug' or 'enhancement'
     */
    type?: 'bug' | 'enhancement';
  }
  /**
   * Feedlog Issues List Component
   * A component for displaying a list of GitHub issues with support for bugs and enhancements.
   */
  interface FeedlogIssuesList {
    /**
     * Empty state message. When provided with emptyStateTitle, shows a richer empty state with illustration.
     */
    emptyStateMessage?: string;
    /**
     * Empty state title. When provided with emptyStateMessage, shows a richer empty state with illustration.
     */
    emptyStateTitle?: string;
    /**
     * Optional callback to resolve GitHub issue URL when githubIssueLink is not available.
     */
    getIssueUrl?: GetIssueUrlFn;
    /**
     * Array of issues to display
     * @default []
     */
    issues?: FeedlogIssueType[];
    /**
     * Page size (items per page). When set, enables pagination when issues exceed this limit.
     */
    limit?: number;
    /**
     * Emitted when an issue is upvoted
     */
    onFeedlogUpvote?: (
      event: FeedlogIssuesListCustomEvent<{
        issueId: string;
        currentUpvoted: boolean;
        currentCount: number;
      }>
    ) => void;
    /**
     * Theme variant: 'light' or 'dark'
     * @default 'light'
     */
    theme?: 'light' | 'dark';
  }
  interface IntrinsicElements {
    'feedlog-badge': FeedlogBadge;
    'feedlog-button': FeedlogButton;
    'feedlog-card': FeedlogCard;
    'feedlog-issue': FeedlogIssue;
    'feedlog-issues': FeedlogIssues;
    'feedlog-issues-client': FeedlogIssuesClient;
    'feedlog-issues-list': FeedlogIssuesList;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      /**
       * Feedlog Badge Component
       * A label component with variant support for different styles.
       */
      'feedlog-badge': LocalJSX.FeedlogBadge & JSXBase.HTMLAttributes<HTMLFeedlogBadgeElement>;
      /**
       * Feedlog Button Component
       * A button component with variant and size support.
       */
      'feedlog-button': LocalJSX.FeedlogButton & JSXBase.HTMLAttributes<HTMLFeedlogButtonElement>;
      /**
       * Feedlog Card Component
       * A reusable card container component with header and content areas.
       */
      'feedlog-card': LocalJSX.FeedlogCard & JSXBase.HTMLAttributes<HTMLFeedlogCardElement>;
      /**
       * Feedlog Issue Component
       * A component for displaying a single GitHub issue.
       */
      'feedlog-issue': LocalJSX.FeedlogIssue & JSXBase.HTMLAttributes<HTMLFeedlogIssueElement>;
      /**
       * Feedlog Issues Component
       * Component for displaying issues with support for bugs and enhancements.
       * Includes full list rendering, loading/error states, and pagination support.
       */
      'feedlog-issues': LocalJSX.FeedlogIssues & JSXBase.HTMLAttributes<HTMLFeedlogIssuesElement>;
      /**
       * Feedlog Issues Client Component
       * A component for displaying issues fetched using the Feedlog SDK.
       * This component uses the SDK internally to fetch data and delegates to feedlog-issues for rendering.
       */
      'feedlog-issues-client': LocalJSX.FeedlogIssuesClient &
        JSXBase.HTMLAttributes<HTMLFeedlogIssuesClientElement>;
      /**
       * Feedlog Issues List Component
       * A component for displaying a list of GitHub issues with support for bugs and enhancements.
       */
      'feedlog-issues-list': LocalJSX.FeedlogIssuesList &
        JSXBase.HTMLAttributes<HTMLFeedlogIssuesListElement>;
    }
  }
}
