/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Feedlog Badge Component
     * A label component with variant support for different styles.
     */
    interface FeedlogBadge {
        /**
          * Badge variant style
          * @default 'default'
         */
        "variant": 'default' | 'destructive';
    }
    /**
     * Feedlog Button Component
     * A button component with variant and size support.
     */
    interface FeedlogButton {
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Button size
          * @default 'default'
         */
        "size": 'default' | 'sm' | 'lg';
        /**
          * Button type
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant style
          * @default 'default'
         */
        "variant": 'default' | 'outline' | 'ghost' | 'destructive';
    }
    /**
     * Feedlog Card Component
     * A reusable card container component with header and content areas.
     */
    interface FeedlogCard {
    }
    /**
     * Feedlog GitHub Issues Component
     * A component for displaying a list of GitHub issues with support for bugs and enhancements.
     */
    interface FeedlogGithubIssues {
        /**
          * Issues data as JSON string or array
         */
        "data"?: string | GitHubIssue[];
        /**
          * Maximum width of the container
          * @default '56rem'
         */
        "maxWidth": string;
    }
}
export interface FeedlogButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFeedlogButtonElement;
}
export interface FeedlogGithubIssuesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFeedlogGithubIssuesElement;
}
declare global {
    /**
     * Feedlog Badge Component
     * A label component with variant support for different styles.
     */
    interface HTMLFeedlogBadgeElement extends Components.FeedlogBadge, HTMLStencilElement {
    }
    var HTMLFeedlogBadgeElement: {
        prototype: HTMLFeedlogBadgeElement;
        new (): HTMLFeedlogBadgeElement;
    };
    interface HTMLFeedlogButtonElementEventMap {
        "feedlogClick": MouseEvent;
    }
    /**
     * Feedlog Button Component
     * A button component with variant and size support.
     */
    interface HTMLFeedlogButtonElement extends Components.FeedlogButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFeedlogButtonElementEventMap>(type: K, listener: (this: HTMLFeedlogButtonElement, ev: FeedlogButtonCustomEvent<HTMLFeedlogButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFeedlogButtonElementEventMap>(type: K, listener: (this: HTMLFeedlogButtonElement, ev: FeedlogButtonCustomEvent<HTMLFeedlogButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFeedlogButtonElement: {
        prototype: HTMLFeedlogButtonElement;
        new (): HTMLFeedlogButtonElement;
    };
    /**
     * Feedlog Card Component
     * A reusable card container component with header and content areas.
     */
    interface HTMLFeedlogCardElement extends Components.FeedlogCard, HTMLStencilElement {
    }
    var HTMLFeedlogCardElement: {
        prototype: HTMLFeedlogCardElement;
        new (): HTMLFeedlogCardElement;
    };
    interface HTMLFeedlogGithubIssuesElementEventMap {
        "feedlogUpvote": number;
    }
    /**
     * Feedlog GitHub Issues Component
     * A component for displaying a list of GitHub issues with support for bugs and enhancements.
     */
    interface HTMLFeedlogGithubIssuesElement extends Components.FeedlogGithubIssues, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFeedlogGithubIssuesElementEventMap>(type: K, listener: (this: HTMLFeedlogGithubIssuesElement, ev: FeedlogGithubIssuesCustomEvent<HTMLFeedlogGithubIssuesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFeedlogGithubIssuesElementEventMap>(type: K, listener: (this: HTMLFeedlogGithubIssuesElement, ev: FeedlogGithubIssuesCustomEvent<HTMLFeedlogGithubIssuesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFeedlogGithubIssuesElement: {
        prototype: HTMLFeedlogGithubIssuesElement;
        new (): HTMLFeedlogGithubIssuesElement;
    };
    interface HTMLElementTagNameMap {
        "feedlog-badge": HTMLFeedlogBadgeElement;
        "feedlog-button": HTMLFeedlogButtonElement;
        "feedlog-card": HTMLFeedlogCardElement;
        "feedlog-github-issues": HTMLFeedlogGithubIssuesElement;
    }
}
declare namespace LocalJSX {
    /**
     * Feedlog Badge Component
     * A label component with variant support for different styles.
     */
    interface FeedlogBadge {
        /**
          * Badge variant style
          * @default 'default'
         */
        "variant"?: 'default' | 'destructive';
    }
    /**
     * Feedlog Button Component
     * A button component with variant and size support.
     */
    interface FeedlogButton {
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Event emitted when button is clicked
         */
        "onFeedlogClick"?: (event: FeedlogButtonCustomEvent<MouseEvent>) => void;
        /**
          * Button size
          * @default 'default'
         */
        "size"?: 'default' | 'sm' | 'lg';
        /**
          * Button type
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant style
          * @default 'default'
         */
        "variant"?: 'default' | 'outline' | 'ghost' | 'destructive';
    }
    /**
     * Feedlog Card Component
     * A reusable card container component with header and content areas.
     */
    interface FeedlogCard {
    }
    /**
     * Feedlog GitHub Issues Component
     * A component for displaying a list of GitHub issues with support for bugs and enhancements.
     */
    interface FeedlogGithubIssues {
        /**
          * Issues data as JSON string or array
         */
        "data"?: string | GitHubIssue[];
        /**
          * Maximum width of the container
          * @default '56rem'
         */
        "maxWidth"?: string;
        /**
          * Event emitted when an issue is upvoted
         */
        "onFeedlogUpvote"?: (event: FeedlogGithubIssuesCustomEvent<number>) => void;
    }
    interface IntrinsicElements {
        "feedlog-badge": FeedlogBadge;
        "feedlog-button": FeedlogButton;
        "feedlog-card": FeedlogCard;
        "feedlog-github-issues": FeedlogGithubIssues;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Feedlog Badge Component
             * A label component with variant support for different styles.
             */
            "feedlog-badge": LocalJSX.FeedlogBadge & JSXBase.HTMLAttributes<HTMLFeedlogBadgeElement>;
            /**
             * Feedlog Button Component
             * A button component with variant and size support.
             */
            "feedlog-button": LocalJSX.FeedlogButton & JSXBase.HTMLAttributes<HTMLFeedlogButtonElement>;
            /**
             * Feedlog Card Component
             * A reusable card container component with header and content areas.
             */
            "feedlog-card": LocalJSX.FeedlogCard & JSXBase.HTMLAttributes<HTMLFeedlogCardElement>;
            /**
             * Feedlog GitHub Issues Component
             * A component for displaying a list of GitHub issues with support for bugs and enhancements.
             */
            "feedlog-github-issues": LocalJSX.FeedlogGithubIssues & JSXBase.HTMLAttributes<HTMLFeedlogGithubIssuesElement>;
        }
    }
}
